### ISSUE TITLE
80% can be better than 100%

### ISSUE THREAD

**Issue by johnrs** [akc3n/akc3n.page#1]
I enjoyed your article, but I have one issue.  I understand the advantages of charging to 100% - when the device knows to cut off any further charging till the battery drops by some amount, perhaps 1%.  As long as the phone is connected to a power source, the battery will see very little use, and this is great.  But "storing" a battery at 100% will cause more decay that storing it at 60%, for example.

Also, let's say that on a typical work day, when my phone is not connected to a power source, that I use 50% of the battery's capacity.  Thus, when I get home, the battery will be at 50%.  Compare this to a phone which is kept between 30% and 80%.  This would stress the battery less - both when discharging and recharging.

But what if you need more than 50% capacity during the day?  Then do what you have to.  But, perhaps you can plug your phone in for a mid-day charge.  This would allow you keep the battery between 30% and 80% (in the example above) and give you a full 100% for the day.  That's MUCH better than running the charge from 100% to 0%!  Note: The phone will stop you before going to 0%, of course.

I've done this manually for years, using a 20/80% program to warn me when I hit 60% (my minimum) , and a timer which my charger plugs into to stop the charge after a fixed number of minutes.  A pain, yes - but consider that I just recently bought a Pixel 8 to replace my Pixel 2.  The Pixel 2 battery, after 6 years of use, has about 90% (Android) or 85% (AccuBattery) of its initial capacity left.

My Pixel won't let me reduce the 100% charging target (without rooting it).  HP laptops used to offer such feature but replaced it with a learning algorithm - which always charges to 100%.

There is one way that you can set your own limit, without rooting the phone:  Use a Chargie, chargie.org.  This comes even closer to the ideal and it's automatic.  Disclaimer: I'm a customer who bought one.  No other connection.

One more thought:  Charging rate is an issue.  The algorithms you mentioned do adjust it based on % charge and temperature.  Good, but if you aren't in a rush then why push it?  You have 8 hours to recharge it at night, right?  I use an old 5V 2A USB-A charger.  The Pixel 8 only runs it at 1A because I have fast charging disabled.  So, even in the mid-range %'s it's low temp charging.

The references I've read say that 50% to 60% is the very best range for the battery's voltage if you want the longest life.  30% to 80% is a good compromise if you need a 50% range.  And it leaves you with 20% (never go below 10%) for unusual situations.  And by keeping a small charger with you (or at the office and in the car) you can probably eliminate just about all of these situations.

My new Pixel 8 gets Google support for 7 years.  I plan to use it for about 10 years.  :)

**Comment by akc3n** [comment]
Thank you for taking the time to share your insights and experiences regarding battery management. It's clear you've put a lot of thought and effort into optimizing the lifespan of your devices. I appreciate the suggestions. I'll keep these points in mind as I continue to explore options for maximizing battery health. Thanks again for your input!
